services:
  rits-db:
    image: rits-db
    ports:
      - 8091:5432
      
  rits-randomizer:
    image: rits-randomizer
    ports:
      - 8090:8010

  rits-client:
    image: rits-client
    depends_on:
      - rits-db
      - rits-randomizer
    ports:
      - 8092:3000
    
#secrets:
#  db_root_password: P05t&4eEs!
#  db_user: rits
#  db_password: 5!4sC5ackerS
#  db_url: postgresql://rits:5!4sC5ackerS@localhost:5432/rits_dev?schema=base

#volumes:
#    rits-volume:
#      external: true
