name: mismat

services:
  randomizer:
    container_name: randomizer
    build:
      context: ./randomizer/
      labels:
        - "com.description=Mismat Randomizer"
    networks:
      - hidden
  db:
    container_name: database
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_DB=mismat_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    secrets:
      - db_user
      - db_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - type: volume
        source: mismat-volume
        target: /var/lib/postgresql
    networks:
      - hidden
    healthcheck:
      test:
        ["CMD-SHELL", "psql -U db_user -d mismat_db -c 'SELECT 1' || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 5
      start_period: 10s
      start_interval: 1s
  client:
    container_name: client
    build:
      context: ./client/
      labels:
        - "com.description=Mismat Web Client"
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db/mismat_db?schema=base
      - RANDOMIZER_URL="localhost:"
    secrets:
      - db_user
      - db_password
    depends_on:
      db:
        condition: service_healthy
      randomizer:
        condition: service_started
    networks:
      - hidden
      - exposed
    ports:
      - "80:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -S localhost:3000/healthz"]
      interval: 1m
      timeout: 20s
      retries: 5
      start_period: 10s
      start_interval: 1s

secrets:
  db_user:
    file: .secret-db_user
  db_password:
    file: .secret-db_password

networks:
  exposed:
    attachable: true
    labels:
      - "com.description=Front End Network for Website Exposure"
  hidden:
    attachable: false
    internal: true
    labels:
      - "com.description=Back End Network for Service Interconnect"
# volumes:
#   mismat-volume:
#     external: true
#   caddy-data:
#     labels:
#       - "com.description=Caddy data volume"
#   caddy-config:
#     labels:
#       - "com.description=Caddy config volume"
