---

# Compose file for authelia testing

secrets:
  JWT_SECRET:
    file: .secret-JWT_SECRET
  SESSION_SECRET:
    file: .secret-SESSION_SECRET
  STORAGE_PASSWORD:
    file: .secret-STORAGE_PASSWORD
  STORAGE_ENCRYPTION_KEY:
    file: .secret-STORAGE_ENCRYPTION_KEY
services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    networks:
      net:
        aliases: []
    expose:
      - 9091
    secrets: ['JWT_SECRET', 'SESSION_SECRET', 'STORAGE_PASSWORD', 'STORAGE_ENCRYPTION_KEY']
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
    volumes:
      - 'configuration.yml:/config/configuration.yml'
networks:
  net:
    external: true
    name: 'net'
...